/** List of EVENTOes */
export const GET_EVENTOS_LIST_REQUEST = 'GET_EVENTOS_LIST_REQUEST';
export const GET_EVENTOS_LIST_SUCCESS = 'GET_EVENTOS_LIST_SUCCESS';

/** EVENTOS form */
export const SET_EVENTO_REQUEST = 'SET_EVENTO_REQUEST';
export const SET_EVENTO_SUCCESS = 'SET_EVENTO_SUCCESS';
export const GET_EVENTOS_MODAL = 'GET_EVENTOS_MODAL';
export const HIDE_EVENTOS_MODAL = 'HIDE_EVENTOS_MODAL';

/** Error */
export const GET_EVENTOS_ERROR = 'GET_EVENTOS_ERROR';