/** List of PROGRAMACIONDEEVENTO */
export const GET_PROGRAMACIONDEEVENTOS_LIST_REQUEST = 'GET_PROGRAMACIONDEEVENTOS_LIST_REQUEST';
export const GET_PROGRAMACIONDEEVENTOS_LIST_SUCCESS = 'GET_PROGRAMACIONDEEVENTOS_LIST_SUCCESS';

/** PROGRAMACIONDEEVENTOS form */
export const SET_PROGRAMACIONDEEVENTO_REQUEST = 'SET_PROGRAMACIONDEEVENTO_REQUEST';
export const SET_PROGRAMACIONDEEVENTO_SUCCESS = 'SET_PROGRAMACIONDEEVENTO_SUCCESS';
export const GET_PROGRAMACIONDEEVENTOS_MODAL = 'GET_PROGRAMACIONDEEVENTOS_MODAL';
export const HIDE_PROGRAMACIONDEEVENTOS_MODAL = 'HIDE_PROGRAMACIONDEEVENTOS_MODAL';
/** Error */
export const GET_PROGRAMACIONDEEVENTOS_ERROR = 'GET_PROGRAMACIONDEEVENTOS_ERROR';
