/** List of ENCUESTOes */
export const GET_ENCUESTOS_LIST_REQUEST = 'GET_ENCUESTOS_LIST_REQUEST';
export const GET_ENCUESTOS_LIST_SUCCESS = 'GET_ENCUESTOS_LIST_SUCCESS';

/** ENCUESTOS form */
export const SET_ENCUESTO_REQUEST = 'SET_ENCUESTO_REQUEST';
export const SET_ENCUESTO_SUCCESS = 'SET_ENCUESTO_SUCCESS';
export const GET_ENCUESTOS_MODAL = 'GET_ENCUESTOS_MODAL';
export const HIDE_ENCUESTOS_MODAL = 'HIDE_ENCUESTOS_MODAL';

/** Error */
export const GET_ENCUESTOS_ERROR = 'GET_ENCUESTOS_ERROR';
